version: '3'
services:
  haproxy:
    image: "haproxy:2.2"
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  weba:
    image: "httpd:2.4"
    ports:
        - "8081:80"
    volumes:
        - ./a.html:/usr/local/apache2/htdocs/index.html
  webb:
    image: "httpd:2.4"
    ports:
        - "8082:80"
    volumes:
        - ./b.html:/usr/local/apache2/htdocs/index.html
  webc:
    image: "httpd:2.4"
    ports:
        - "8083:80"
    volumes:
        - ./c.html:/usr/local/apache2/htdocs/index.html